import { Logbook } from "./logbook";
export const exampleLogbook: Logbook = {
  date: new Date('2025-03-12T00:00:00Z'),
  initials: "JD",
  increments: [
    { dutyStatus: "OFF DUTY" },
    { dutyStatus: "OFF DUTY" },
    { dutyStatus: "OFF DUTY" },
    { dutyStatus: "OFF DUTY" },
    { dutyStatus: "OFF DUTY" },
    {
      dutyStatus: "ON DUTY",
      remark: {
        city: "San Jose",
        state: "CA",
        commodity: "Electronics",
        detail: "Waiting for loading at dock",
        latitude: 37.3382,
        longitude: -121.8863,
      },
    },
    { dutyStatus: "DRIVING" },
    { dutyStatus: "DRIVING" },
    { dutyStatus: "DRIVING" },
    { dutyStatus: "DRIVING" },
    {
      dutyStatus: "ON DUTY",
      remark: {
        city: "San Francisco",
        state: "CA",
        commodity: "Electronics",
        detail: "Unloading cargo at warehouse",
        latitude: 37.7749,
        longitude: -122.4194,
      },
    },
    { dutyStatus: "ON DUTY" },
    { dutyStatus: "ON DUTY" },
    { dutyStatus: "ON DUTY" },
    { dutyStatus: "ON DUTY" },
    { dutyStatus: "ON DUTY" },
    { dutyStatus: "ON DUTY" },
    {
      dutyStatus: "OFF DUTY",
      remark: {
        city: "San Francisco",
        state: "CA",
        commodity: "Electronics",
        detail: "Taking break at truck stop",
        latitude: 37.7749,
        longitude: -122.4194,
      },
    },
    { dutyStatus: "OFF DUTY" },
    { dutyStatus: "OFF DUTY" },
    { dutyStatus: "OFF DUTY" },
    { dutyStatus: "OFF DUTY" },
    { dutyStatus: "OFF DUTY" },
    {
      dutyStatus: "ON DUTY",
      remark: {
        city: "San Jose",
        state: "CA",
        commodity: "Electronics",
        detail: "Waiting for loading at dock",
        latitude: 37.3382,
        longitude: -121.8863,
      },
    },
    { dutyStatus: "DRIVING" },
    { dutyStatus: "DRIVING" },
    { dutyStatus: "DRIVING" },
    { dutyStatus: "DRIVING" },
    { dutyStatus: "DRIVING" },
    { dutyStatus: "DRIVING" },
    {
      dutyStatus: "ON DUTY",
      remark: {
        city: "San Jose",
        state: "CA",
        commodity: "Electronics",
        detail: "Waiting for loading at dock",
        latitude: 37.3382,
        longitude: -121.8863,
      },
    },
    { dutyStatus: "ON DUTY" },
    { dutyStatus: "ON DUTY" },
    { dutyStatus: "ON DUTY" },
    { dutyStatus: "ON DUTY" },
    { dutyStatus: "ON DUTY" },
    { dutyStatus: "ON DUTY" },
    {
      dutyStatus: "OFF DUTY",
      remark: {
        city: "San Jose",
        state: "CA",
        commodity: "Electronics",
        detail: "Resting after driving",
        latitude: 37.3382,
        longitude: -121.8863,
      },
    },
    { dutyStatus: "OFF DUTY" },
    { dutyStatus: "OFF DUTY" },
    { dutyStatus: "OFF DUTY" },
    { dutyStatus: "OFF DUTY" },
    { dutyStatus: "OFF DUTY" },
    { dutyStatus: "OFF DUTY" },
    { dutyStatus: "OFF DUTY" },
    { dutyStatus: "OFF DUTY" },
    { dutyStatus: "OFF DUTY" },
    { dutyStatus: "DRIVING" },
  ],
};
