import { Geist, Geist_Mono } from "next/font/google";
import { PlusIcon } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full`}
      >
        <nav className="h-20 w-full flex justify-between items-center border-b">
          <div className="w-48">

          </div>
          <div className="flex-1 flex gap-8">
            <Link href="/trip" className="block w-32 px-4 py-2 bg-neutral-100/10 hover:bg-neutral-100 border-b-2 border-neutral-500 rounded-t-3xl rounded-b text-lg text-center transition">
              Trips
            </Link>
          </div>
          <div className="w-48 pr-12 flex justify-end items-center">
            <Link href="/trip/new" className="rounded-full hover:scale-105 border-neutral-800 border-2 transition">
                <PlusIcon className="hover:stroke-3 stroke-2 transition" stroke="#262626" size={36} />
              </Link>
          </div>
        </nav>
        <div className="flex">
          <div className="hidden md:block max-w-[3rem] w-64 hover:max-w-[16rem] transition-[max-width]"></div>
          <div className="min-h[calc(100vh - 5rem)] pl-2 pt-2 border-l">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
